import { MenuItem } from "@/components/MenuCard";

export const mockMenuItems: MenuItem[] = [
  {
    id: "1",
    name: "Butter Chicken",
    description: "Creamy tomato-based curry with tender chicken pieces",
    price: 299,
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    category: "Main Course",
    available: true,
    isVeg: false,
  },
  {
    id: "2",
    name: "Paneer Tikka Masala",
    description: "Grilled cottage cheese in rich spiced gravy",
    price: 249,
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400",
    category: "Main Course",
    available: true,
    isVeg: true,
  },
  {
    id: "3",
    name: "Biryani Special",
    description: "Aromatic basmati rice with spiced meat and saffron",
    price: 349,
    image: "https://images.unsplash.com/photo-1563379091339-03246963d25a?w=400",
    category: "Rice",
    available: true,
    isVeg: false,
  },
  {
    id: "4",
    name: "Masala Dosa",
    description: "Crispy crepe filled with spiced potato curry",
    price: 149,
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=400",
    category: "South Indian",
    available: true,
    isVeg: true,
  },
  {
    id: "5",
    name: "Gulab Jamun",
    description: "Sweet milk dumplings in sugar syrup",
    price: 99,
    image: "https://images.unsplash.com/photo-1626132647523-66f3bf8f4d04?w=400",
    category: "Desserts",
    available: false,
    isVeg: true,
  },
  {
    id: "6",
    name: "Caesar Salad",
    description: "Fresh romaine lettuce with Caesar dressing, croutons, and Parmesan cheese.",
    price: 199,
    image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400",
    category: "Salads",
    available: true,
    isVeg: true,
  },
  {
    id: "7",
    name: "Spaghetti Carbonara",
    description: "Classic Italian pasta with eggs, cheese, pancetta, and black pepper.",
    price: 329,
    image: "https://images.unsplash.com/photo-1608796316151-37a4ea8e8a69?w=400",
    category: "Main Course",
    available: true,
    isVeg: false,
  },
  {
    id: "8",
    name: "Chocolate Lava Cake",
    description: "Warm, gooey chocolate cake with a molten center.",
    price: 129,
    image: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?w=400",
    category: "Desserts",
    available: true,
    isVeg: true,
  },
];
